name: Missing STAR
description: For missing star's when the airport xml exists
title: "Missing STAR [Airport ICAO] [STAR Name]"
labels: ["STAR", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        # If your airport does not have a properties file, this is not the template for you
  - type: checkboxes
    id: file-exists
    attributes:
      label: The File Exists
      description: You have checked, and there is a .properties.xml for this airport
      options:
        - label: I confirm that this is about a file that exists in this repo, and not a missing file
          required: true
  - type: input
    id: airport-icao
    attributes:
      label: Airport ICAO
    validations:
      required: true
  - type: input
    id: star-name
    attributes:
      label: star Name
    validations:
      required: true
  - type: input
    id: star-transition
    attributes:
      label: STAR Transition
      description: This can be a runway transition or a regular transition
    validations:
      required: false
  - type: input
    id: star-chart
    attributes:
      label: star-chart
      description: Please find the chart for this STAR from [this site](https://www.airnav.com/airport)
    validations:
      required: true