name: Missing Approach
description: For missing aprroaches when the airport xml exists
title: "Missing Approach [Airport ICAO] [Approach Name]"
labels: ["Approach", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        # If your airport does not have a properties file, this is not the template for you
  - type: checkboxes
    id: file-exists
    attributes:
      label: The File Exists
      description: You have checked, and there is a .properties.xml for this airport
      options:
        - label: I confirm that this is about a file that exists in this repo, and not a missing file
          required: true
  - type: input
    id: airport-icao
    attributes:
      label: Airport ICAO
    validations:
      required: true
  - type: input
    id: approach-name
    attributes:
      label: Approach Name
    validations:
      required: true
  - type: input
    id: approach-chart
    attributes:
      label: Approach Name
      description: Please find the chart for this approach from [this site](https://www.airnav.com/airport)
    validations:
      required: true