name: Missing SID
description: For missing sid's when the airport xml exists
title: "Missing SID [Airport ICAO] [SID Name]"
labels: ["SID", "untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        # If your airport does not have a properties file, this is not the template for you
  - type: checkboxes
    id: file-exists
    attributes:
      label: The File Exists
      description: You have checked, and there is a .properties.xml for this airport
      options:
        - label: I confirm that this is about a file that exists in this repo, and not a missing file
          required: true
  - type: input
    id: airport-icao
    attributes:
      label: Airport ICAO
    validations:
      required: true
  - type: input
    id: sid-name
    attributes:
      label: SID Name
    validations:
      required: true
  - type: input
    id: sid-transition
    attributes:
      label: SID Transition
      description: This can be a runway transition or a regular transition
    validations:
      required: false
  - type: input
    id: sid-chart
    attributes:
      label: sid-chart
      description: Please find the chart for this sid from [this site](https://www.airnav.com/airport)
    validations:
      required: true