name: Something Unexpected Happened
description: My Autopilot came up with a strange route
title: "Something Unexpected Happened Whilst Flying [Airport ICAO] [SID/STAR/Approach Name] [SID/STAR Transition (if applicable)]"
labels: ["untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Note that this may be an issue with your aircraft, and not this data. We appreciate you reporting it regardless.
  - type: input
    id: airport-icao
    attributes:
      label: Airport ICAO
    validations:
      required: true
  - type: checkboxes
    id: route-type
    attributes:
      label: What kind of approach was this?
      options:
        - label: SID
        - label: STAR
        - label: Approach
          required: true
  - type: input
    id: transition-name
    attributes:
      description: Include this **only if** the unexpected behavior was in the transition
      label: Transition Name
  - type: input
    id: star-transition
    attributes:
      label: STAR Transition
      description: This can be a runway transition or a regular transition
    validations:
      required: false
  - type: input
    id: star-chart
    attributes:
      label: star-chart
      description: Please find the chart for this STAR from [this site](https://www.airnav.com/airport)
    validations:
      required: true
  - type: input
    id: updated-title
    attributes:
      label: I have updated the title
      description: Check this box to confirm that you replaced the template in the title
    validations:
      required: true