name: Something Unexpected Happened
description: My Autopilot came up with a strange route
title: "Something Unexpected Happened Whilst Flying [Airport ICAO] [SID/STAR/Approach Name] [SID/STAR Transition (if applicable)]"
labels: ["untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Note that this may be an issue with your aircraft, and not this data. We appreciate you reporting it regardless.
  - type: input
    id: airport-icao
    attributes:
      label: Airport ICAO
    validations:
      required: true
  - type: dropdown
    id: route-type
    attributes:
      label: What part of the flight was this?
      multiple: false
      options:
        - SID
        - STAR
        - Approach
        - I don't know
    validations:
      required: true
  - type: input
    id: procedure-name
    attributes:
      label: Procedure Name
      description: This can be the name of a SID/STAR/Approach, whichever is to blame for your issue
    validations:
      required: true
  - type: input
    id: transition-name
    attributes:
      description: Include this **only if** the unexpected behavior was in the transition
      label: Transition Name
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Please explain in as much detail as possible what the unexpected behavior is. A screenshot is desired if possible as well as an explanation on how to reproduce the issue including **aircraft** used and route flown.
  - type: checkboxes
    id: updated-title
    attributes:
      label: Did I update the title?
      options:
        - label: Yes, I have replaced the templates in the title of this issue
          required: true