name: Update to new airac cycle

# Run at 0905Z every day to check if the FAA just activated a new AIRAC which happens at 0901Z
#on:
#  schedule:
#    -  cron: '10 22 * * *'
on: [workflow_dispatch]

jobs:
  check_cycle:
    runs-on: ubuntu-latest
    name: Check for new airac
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - id: should_run
        continue-on-error: true
        name: check for new airac
        run: curl --fail -I -s "https://aeronav.faa.gov/Upload_313-d/cifp/CIFP_$(date +"%y%m%d").zip" > /dev/null || echo "::set-output name=should_run::false"

  run:
    needs: check_cycle
    if: ${{ needs.check_cycle.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout project
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: get new cifp
        run: wget "https://aeronav.faa.gov/Upload_313-d/cifp/CIFP_$(date +"%y%m%d").zip" && unzip -o "CIFP_$(date +"%y%m%d").zip" FAACIFP18 -d current_cifp

      - name: run index
        run: node index.js

      - name: Set commit name variable
        run: |
          echo "COMMIT_TITLE=AUTOMATIC: Update to $(date +"%y%m%d") cycle" >> $GITHUB_ENV

      - name: commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          create_branch: false
          commit_message: ${{ env.COMMIT_TITLE }}
